//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-04-22 - 18:11:38
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using OrderWala.Domain;
using OrderWala.DAL;

namespace OrderWala.DAL
{

    /// <summary>
    /// Assembler for <see cref="tblAdvertisement"/> and <see cref="tblAdvertisementDTO"/>.
    /// </summary>
    public static partial class tblAdvertisementAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblAdvertisementDTO"/> converted from <see cref="tblAdvertisement"/>.</param>
        static partial void OnDTO(this tblAdvertisement entity, tblAdvertisementDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblAdvertisement"/> converted from <see cref="tblAdvertisementDTO"/>.</param>
        static partial void OnEntity(this tblAdvertisementDTO dto, tblAdvertisement entity);

        /// <summary>
        /// Converts this instance of <see cref="tblAdvertisementDTO"/> to an instance of <see cref="tblAdvertisement"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblAdvertisementDTO"/> to convert.</param>
        public static tblAdvertisement ToEntity(this tblAdvertisementDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblAdvertisement();

            entity.AdvertisementId = dto.AdvertisementId;
            entity.AdvertisementName = dto.AdvertisementName;
            entity.CompanyName = dto.CompanyName;
            entity.Description = dto.Description;
            entity.Weblink = dto.Weblink;
            entity.StartDateTime = dto.StartDateTime;
            entity.EndDateTime = dto.EndDateTime;
            entity.IsActive = dto.IsActive;
            entity.IsDeleted = dto.IsDeleted;
            entity.CreationDateTime = dto.CreationDateTime;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblAdvertisement"/> to an instance of <see cref="tblAdvertisementDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblAdvertisement"/> to convert.</param>
        public static tblAdvertisementDTO ToDTO(this tblAdvertisement entity)
        {
            if (entity == null) return null;

            var dto = new tblAdvertisementDTO();

            dto.AdvertisementId = entity.AdvertisementId;
            dto.AdvertisementName = entity.AdvertisementName;
            dto.CompanyName = entity.CompanyName;
            dto.Description = entity.Description;
            dto.Weblink = entity.Weblink;
            dto.StartDateTime = entity.StartDateTime;
            dto.EndDateTime = entity.EndDateTime;
            dto.IsActive = entity.IsActive;
            dto.IsDeleted = entity.IsDeleted;
            dto.CreationDateTime = entity.CreationDateTime;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblAdvertisementDTO"/> to an instance of <see cref="tblAdvertisement"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblAdvertisement> ToEntities(this IEnumerable<tblAdvertisementDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblAdvertisement"/> to an instance of <see cref="tblAdvertisementDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblAdvertisementDTO> ToDTOs(this IEnumerable<tblAdvertisement> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
