//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-04-17 - 08:15:06
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using OrderWala.Domain;
using OrderWala.DAL;

namespace OrderWala.DAL
{

    /// <summary>
    /// Assembler for <see cref="tblCustomer"/> and <see cref="tblCustomerDTO"/>.
    /// </summary>
    public static partial class tblCustomerAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblCustomerDTO"/> converted from <see cref="tblCustomer"/>.</param>
        static partial void OnDTO(this tblCustomer entity, tblCustomerDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblCustomer"/> converted from <see cref="tblCustomerDTO"/>.</param>
        static partial void OnEntity(this tblCustomerDTO dto, tblCustomer entity);

        /// <summary>
        /// Converts this instance of <see cref="tblCustomerDTO"/> to an instance of <see cref="tblCustomer"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblCustomerDTO"/> to convert.</param>
        public static tblCustomer ToEntity(this tblCustomerDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblCustomer();

            entity.CustomerId = dto.CustomerId;
            entity.FirstName = dto.FirstName;
            entity.LastName = dto.LastName;
            entity.Address = dto.Address;
            entity.CityId = dto.CityId;
            entity.EmailAddress = dto.EmailAddress;
            entity.MobileNo = dto.MobileNo;
            entity.Latitude = dto.Latitude;
            entity.Longitude = dto.Longitude;
            entity.TotalOrderAmount = dto.TotalOrderAmount;
            entity.RecievedAmount = dto.RecievedAmount;
            entity.IsActive = dto.IsActive;
            entity.IsDeleted = dto.IsDeleted;
            entity.CreationDateTime = dto.CreationDateTime;
            entity.RegisterDeviceFrom = dto.RegisterDeviceFrom;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblCustomer"/> to an instance of <see cref="tblCustomerDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblCustomer"/> to convert.</param>
        public static tblCustomerDTO ToDTO(this tblCustomer entity)
        {
            if (entity == null) return null;

            var dto = new tblCustomerDTO();

            dto.CustomerId = entity.CustomerId;
            dto.FirstName = entity.FirstName;
            dto.LastName = entity.LastName;
            dto.Address = entity.Address;
            dto.CityId = entity.CityId;
            dto.EmailAddress = entity.EmailAddress;
            dto.MobileNo = entity.MobileNo;
            dto.Latitude = entity.Latitude;
            dto.Longitude = entity.Longitude;
            dto.TotalOrderAmount = entity.TotalOrderAmount;
            dto.RecievedAmount = entity.RecievedAmount;
            dto.IsActive = entity.IsActive;
            dto.IsDeleted = entity.IsDeleted;
            dto.CreationDateTime = entity.CreationDateTime;
            dto.RegisterDeviceFrom = entity.RegisterDeviceFrom;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblCustomerDTO"/> to an instance of <see cref="tblCustomer"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblCustomer> ToEntities(this IEnumerable<tblCustomerDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblCustomer"/> to an instance of <see cref="tblCustomerDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblCustomerDTO> ToDTOs(this IEnumerable<tblCustomer> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
