//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-04-22 - 18:46:07
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using OrderWala.Domain;

namespace OrderWala.DAL
{

    /// <summary>
    /// Assembler for <see cref="tblLogin"/> and <see cref="tblLoginDTO"/>.
    /// </summary>
    public static partial class tblLoginAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblLoginDTO"/> converted from <see cref="tblLogin"/>.</param>
        static partial void OnDTO(this tblLogin entity, tblLoginDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblLogin"/> converted from <see cref="tblLoginDTO"/>.</param>
        static partial void OnEntity(this tblLoginDTO dto, tblLogin entity);

        /// <summary>
        /// Converts this instance of <see cref="tblLoginDTO"/> to an instance of <see cref="tblLogin"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblLoginDTO"/> to convert.</param>
        public static tblLogin ToEntity(this tblLoginDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblLogin();

            entity.UserId = dto.UserId;
            entity.MobileNo = dto.MobileNo;
            entity.UserTypeId = dto.UserTypeId;
            entity.CreationDatetime = dto.CreationDatetime;
            entity.Password = dto.Password;
            entity.IsActive = dto.IsActive;
            entity.RegisterDeviceId = dto.RegisterDeviceId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblLogin"/> to an instance of <see cref="tblLoginDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblLogin"/> to convert.</param>
        public static tblLoginDTO ToDTO(this tblLogin entity)
        {
            if (entity == null) return null;

            var dto = new tblLoginDTO();

            dto.UserId = entity.UserId;
            dto.MobileNo = entity.MobileNo;
            dto.UserTypeId = entity.UserTypeId;
            dto.CreationDatetime = entity.CreationDatetime;
            dto.Password = entity.Password;
            dto.IsActive = entity.IsActive;
            dto.RegisterDeviceId = entity.RegisterDeviceId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblLoginDTO"/> to an instance of <see cref="tblLogin"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblLogin> ToEntities(this IEnumerable<tblLoginDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblLogin"/> to an instance of <see cref="tblLoginDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblLoginDTO> ToDTOs(this IEnumerable<tblLogin> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
