//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-04-22 - 18:46:08
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using OrderWala.Domain;

namespace OrderWala.DAL
{

    /// <summary>
    /// Assembler for <see cref="tblSubCategory"/> and <see cref="tblSubCategoryDTO"/>.
    /// </summary>
    public static partial class tblSubCategoryAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblSubCategoryDTO"/> converted from <see cref="tblSubCategory"/>.</param>
        static partial void OnDTO(this tblSubCategory entity, tblSubCategoryDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblSubCategory"/> converted from <see cref="tblSubCategoryDTO"/>.</param>
        static partial void OnEntity(this tblSubCategoryDTO dto, tblSubCategory entity);

        /// <summary>
        /// Converts this instance of <see cref="tblSubCategoryDTO"/> to an instance of <see cref="tblSubCategory"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblSubCategoryDTO"/> to convert.</param>
        public static tblSubCategory ToEntity(this tblSubCategoryDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblSubCategory();

            entity.SubCategoryId = dto.SubCategoryId;
            entity.CategoryId = dto.CategoryId;
            entity.LanguageId = dto.LanguageId;
            entity.SubCategoryName = dto.SubCategoryName;
            entity.Description = dto.Description;
            entity.Logo = dto.Logo;
            entity.IsActive = dto.IsActive;
            entity.IsDeleted = dto.IsDeleted;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblSubCategory"/> to an instance of <see cref="tblSubCategoryDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblSubCategory"/> to convert.</param>
        public static tblSubCategoryDTO ToDTO(this tblSubCategory entity)
        {
            if (entity == null) return null;

            var dto = new tblSubCategoryDTO();

            dto.SubCategoryId = entity.SubCategoryId;
            dto.CategoryId = entity.CategoryId;
            dto.LanguageId = entity.LanguageId;
            dto.SubCategoryName = entity.SubCategoryName;
            dto.Description = entity.Description;
            dto.Logo = entity.Logo;
            dto.IsActive = entity.IsActive;
            dto.IsDeleted = entity.IsDeleted;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblSubCategoryDTO"/> to an instance of <see cref="tblSubCategory"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblSubCategory> ToEntities(this IEnumerable<tblSubCategoryDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblSubCategory"/> to an instance of <see cref="tblSubCategoryDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblSubCategoryDTO> ToDTOs(this IEnumerable<tblSubCategory> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
