//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-04-22 - 18:11:39
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using OrderWala.Domain;
using OrderWala.DAL;

namespace OrderWala.DAL
{

    /// <summary>
    /// Assembler for <see cref="tblUserType"/> and <see cref="tblUserTypeDTO"/>.
    /// </summary>
    public static partial class tblUserTypeAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblUserTypeDTO"/> converted from <see cref="tblUserType"/>.</param>
        static partial void OnDTO(this tblUserType entity, tblUserTypeDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblUserType"/> converted from <see cref="tblUserTypeDTO"/>.</param>
        static partial void OnEntity(this tblUserTypeDTO dto, tblUserType entity);

        /// <summary>
        /// Converts this instance of <see cref="tblUserTypeDTO"/> to an instance of <see cref="tblUserType"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblUserTypeDTO"/> to convert.</param>
        public static tblUserType ToEntity(this tblUserTypeDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblUserType();

            entity.UserTypeId = dto.UserTypeId;
            entity.TypeName = dto.TypeName;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblUserType"/> to an instance of <see cref="tblUserTypeDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblUserType"/> to convert.</param>
        public static tblUserTypeDTO ToDTO(this tblUserType entity)
        {
            if (entity == null) return null;

            var dto = new tblUserTypeDTO();

            dto.UserTypeId = entity.UserTypeId;
            dto.TypeName = entity.TypeName;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblUserTypeDTO"/> to an instance of <see cref="tblUserType"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblUserType> ToEntities(this IEnumerable<tblUserTypeDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblUserType"/> to an instance of <see cref="tblUserTypeDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblUserTypeDTO> ToDTOs(this IEnumerable<tblUserType> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
