//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLanguageMaster
    {
        public TblLanguageMaster()
        {
            this.TblSupplierMasters = new HashSet<TblSupplierMaster>();
        }
    
        public int LanguageID { get; set; }
        public string Language { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<TblSupplierMaster> TblSupplierMasters { get; set; }
    }
}
