//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TblUserLoginMaster
    {
        public int UserID { get; set; }

        [Required(ErrorMessage = "Please Enter Supplier name or  Customer name as a Mobile  Number")]
        [StringLength(10, ErrorMessage = "Maximum  Must Be 10 Digit", MinimumLength = 10)]
        [RegularExpression(@"^([0-9])+$", ErrorMessage = "Please Enter Digit")]
        public string UserName { get; set; }

          [Required(ErrorMessage = "Please Enter Password")]
        public string Password { get; set; }

          [Required(ErrorMessage = "Please select User type")]
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> ConformationCode { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
