//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-04-22 - 18:46:02
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace OrderWala.Domain
{
    [DataContract()]
    public partial class tblAdvertisementDTO
    {
        [DataMember()]
        public Int32 AdvertisementId { get; set; }

        [DataMember()]
        public String AdvertisementName { get; set; }

        [DataMember()]
        public String CompanyName { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public String Weblink { get; set; }

        [DataMember()]
        public Nullable<DateTime> StartDateTime { get; set; }

        [DataMember()]
        public Nullable<DateTime> EndDateTime { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsDeleted { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTime { get; set; }

        public tblAdvertisementDTO()
        {
        }

        public tblAdvertisementDTO(Int32 advertisementId, String advertisementName, String companyName, String description, String weblink, Nullable<DateTime> startDateTime, Nullable<DateTime> endDateTime, Nullable<Boolean> isActive, Nullable<Boolean> isDeleted, Nullable<DateTime> creationDateTime)
        {
			this.AdvertisementId = advertisementId;
			this.AdvertisementName = advertisementName;
			this.CompanyName = companyName;
			this.Description = description;
			this.Weblink = weblink;
			this.StartDateTime = startDateTime;
			this.EndDateTime = endDateTime;
			this.IsActive = isActive;
			this.IsDeleted = isDeleted;
			this.CreationDateTime = creationDateTime;
        }
    }
}
