//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/05/07 - 17:17:06
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace OrderWala.Domain
{
    [DataContract()]
    public partial class tblAreaDTO
    {
        [DataMember()]
        public Int32 AreaId { get; set; }

        [DataMember()]
        public String AreaName { get; set; }

        [DataMember()]
        public Int32 CityId { get; set; }

        [DataMember()]
        public Int32 StateId { get; set; }

        [DataMember()]
        public String Description { get; set; }

        public tblAreaDTO()
        {
        }

        public tblAreaDTO(Int32 areaId, String areaName, Int32 cityId, Int32 stateId, String description)
        {
			this.AreaId = areaId;
			this.AreaName = areaName;
			this.CityId = cityId;
			this.StateId = stateId;
			this.Description = description;
        }
    }
}
