//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-04-22 - 18:46:04
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace OrderWala.Domain
{
    [DataContract()]
    public partial class tblCustomerDTO
    {
        [DataMember()]
        public Int32 CustomerId { get; set; }

        [DataMember()]
        public Int32 UserId { get; set; }

        [DataMember()]
        public String FirstName { get; set; }

        [DataMember()]
        public String LastName { get; set; }

        [DataMember()]
        public String Address { get; set; }

        [DataMember()]
        public Int32 AreaId { get; set; }

        [DataMember()]
        public String EmailAddress { get; set; }

        [DataMember()]
        public String MobileNo { get; set; }

        [DataMember()]
        public String Latitude { get; set; }

        [DataMember()]
        public String Longitude { get; set; }

        [DataMember()]
        public Double TotalOrderAmount { get; set; }

        [DataMember()]
        public Double RecievedAmount { get; set; }

        [DataMember()]
        public Boolean IsActive { get; set; }

        [DataMember()]
        public Boolean IsDeleted { get; set; }

        [DataMember()]
        public DateTime CreationDateTime { get; set; }

        public tblCustomerDTO()
        {
        }

        public tblCustomerDTO(Int32 customerId, Int32 userId, String firstName, String lastName, String address, Int32 areaId, String emailAddress, String mobileNo, String latitude, String longitude, Double totalOrderAmount, Double recievedAmount, Boolean isActive, Boolean isDeleted, DateTime creationDateTime)
        {
			this.CustomerId = customerId;
			this.UserId = userId;
			this.FirstName = firstName;
			this.LastName = lastName;
			this.Address = address;
			this.AreaId = areaId;
			this.EmailAddress = emailAddress;
			this.MobileNo = mobileNo;
			this.Latitude = latitude;
			this.Longitude = longitude;
			this.TotalOrderAmount = totalOrderAmount;
			this.RecievedAmount = recievedAmount;
			this.IsActive = isActive;
			this.IsDeleted = isDeleted;
			this.CreationDateTime = creationDateTime;
        }
    }
}
