//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/05/07 - 17:17:09
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace OrderWala.Domain
{
    [DataContract()]
    public partial class tblDeviceTypeDTO
    {
        [DataMember()]
        public Int32 DeviceId { get; set; }

        [DataMember()]
        public String DeviceType { get; set; }

        public tblDeviceTypeDTO()
        {
        }

        public tblDeviceTypeDTO(Int32 deviceId, String deviceType)
        {
			this.DeviceId = deviceId;
			this.DeviceType = deviceType;
        }
    }
}
