//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-05-07 - 11:56:52
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace OrderWala.Domain
{
    [DataContract()]
    public partial class tblLanguageWiseSubCategoryDTO
    {
        [DataMember()]
        public Int32 RowId { get; set; }

        [DataMember()]
        public Int32 SubCategoryId { get; set; }

        [DataMember()]
        public String SubCategoryName { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public Int32 LanguageId { get; set; }

        public String Logo { get; set; }

        public Int32 CategoryId { get; set; }
        public String Categoryname { get; set; }

        public tblLanguageWiseSubCategoryDTO()
        {
        }

        public tblLanguageWiseSubCategoryDTO(Int32 rowId, Int32 subCategoryId, String subCategoryName, String description, Int32 languageId)
        {
			this.RowId = rowId;
			this.SubCategoryId = subCategoryId;
			this.SubCategoryName = subCategoryName;
			this.Description = description;
			this.LanguageId = languageId;
        }
    }
}
