//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-04-22 - 18:46:05
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace OrderWala.Domain
{
    [DataContract()]
    public partial class tblLoginDTO
    {
        [DataMember()]
        public Int32 UserId { get; set; }

        [DataMember()]
        public String MobileNo { get; set; }

        [DataMember()]
        public Int32 UserTypeId { get; set; }

        [DataMember()]
        public DateTime CreationDatetime { get; set; }

        [DataMember()]
        public String Password { get; set; }

        [DataMember()]
        public Boolean IsActive { get; set; }

        [DataMember()]
        public Int32 RegisterDeviceId { get; set; }

        public tblLoginDTO()
        {
        }

        public tblLoginDTO(Int32 userId, String mobileNo, Int32 userTypeId, DateTime creationDatetime, String password, Boolean isActive, Int32 registerDeviceId)
        {
			this.UserId = userId;
			this.MobileNo = mobileNo;
			this.UserTypeId = userTypeId;
			this.CreationDatetime = creationDatetime;
			this.Password = password;
			this.IsActive = isActive;
			this.RegisterDeviceId = registerDeviceId;
        }
    }
}
