//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-04-17 - 08:15:02
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace OrderWala.Domain.DTO
{
    [DataContract()]
    public partial class tblLanguageWiseProductDTO
    {
        [DataMember()]
        public Int32 RowId { get; set; }

        [DataMember()]
        public Nullable<Int32> ProductId { get; set; }

        [DataMember()]
        public Nullable<Int32> LanguageId { get; set; }

        [DataMember()]
        public String ProductName { get; set; }

        [DataMember()]
        public String Description { get; set; }

        public tblLanguageWiseProductDTO()
        {
        }

        public tblLanguageWiseProductDTO(Int32 rowId, Nullable<Int32> productId, Nullable<Int32> languageId, String productName, String description)
        {
			this.RowId = rowId;
			this.ProductId = productId;
			this.LanguageId = languageId;
			this.ProductName = productName;
			this.Description = description;
        }
    }
}
