//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-04-22 - 18:11:37
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace OrderWala.Domain
{
    [DataContract()]
    public partial class tblLoginDTO
    {
        [DataMember()]
        public Int32 UserId { get; set; }

        [DataMember()]
        public String MobileNo { get; set; }

        [DataMember()]
        public Nullable<Int32> UserTypeId { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDatetime { get; set; }

        [DataMember()]
        public String Password { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        public tblLoginDTO()
        {
        }

        public tblLoginDTO(Int32 userId, String mobileNo, Nullable<Int32> userTypeId, Nullable<DateTime> creationDatetime, String password, Nullable<Boolean> isActive)
        {
			this.UserId = userId;
			this.MobileNo = mobileNo;
			this.UserTypeId = userTypeId;
			this.CreationDatetime = creationDatetime;
			this.Password = password;
			this.IsActive = isActive;
        }
    }
}
