//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/05/07 - 17:17:10
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace OrderWala.Domain
{
    [DataContract()]
    public partial class tblLanguageWiseProductDTO
    {

        public tblLanguageWiseProductDTO()
        {
           
        }

        [DataMember()]
        public Int32 RowId { get; set; }

        public Int32 CategoryID { get; set; }
        public Int32 SubCategoryID { get; set; }
        public Int32 QuantityID { get; set; }

        public String categoryname { get; set; }
        public String Subcategoryname { get; set; }
        public String Quantity { get; set; }
        public String Logo { get; set; }

        [DataMember()]
        public Nullable<Int32> ProductId { get; set; }

        [DataMember()]
        public Nullable<Int32> LanguageId { get; set; }

        public String Language { get; set; }

        [DataMember()]
        public String ProductName { get; set; }

        [DataMember()]
        public String Description { get; set; }

        

    }
}
