//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-05-07 - 11:56:52
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace OrderWala.Domain
{
    [DataContract()]
    public partial class tblLanguageWiseCategoryDTO
    {
        [DataMember()]
        public Int32 RowId { get; set; }

        [DataMember()]
        public Int32 CategoryId { get; set; }

        [DataMember()]
        public String CategoryName { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public Int32 LanguageId { get; set; }

        public tblLanguageWiseCategoryDTO()
        {
        }

        public tblLanguageWiseCategoryDTO(Int32 rowId, Int32 categoryId, String categoryName, String description, Int32 languageId)
        {
			this.RowId = rowId;
			this.CategoryId = categoryId;
			this.CategoryName = categoryName;
			this.Description = description;
			this.LanguageId = languageId;
        }
    }
}
