//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-04-22 - 18:46:05
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace OrderWala.Domain
{
    [DataContract()]
    public partial class tblOrderDTO
    {
        [DataMember()]
        public Int32 OrderId { get; set; }

        [DataMember()]
        public DateTime OrderDateTime { get; set; }

        [DataMember()]
        public Int32 OrderStatus { get; set; }

        [DataMember()]
        public Double OrderAmount { get; set; }

        [DataMember()]
        public Int32 CustomerId { get; set; }

        [DataMember()]
        public Double DeliveryCharges { get; set; }

        [DataMember()]
        public Double OtherCharges { get; set; }

        [DataMember()]
        public String CustomerMessage { get; set; }

        [DataMember()]
        public String OverMessage { get; set; }

        public List<tblOrderItemDTO> OrderItemList { get; set; }
    }
}
