//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-04-17 - 08:15:05
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace OrderWala.Domain
{
    [DataContract()]
    public partial class tblSubCategoryDTO
    {
        [DataMember()]
        public Int32 SubCategoryId { get; set; }

        [DataMember()]
        public Int32 CategoryId { get; set; }

        [DataMember()]
        public Int32 LanguageId { get; set; }

        [DataMember()]
        public String SubCategoryName { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public String Logo { get; set; }

        [DataMember()]
        public Boolean IsActive { get; set; }

        [DataMember()]
        public Boolean IsDeleted { get; set; }

        public tblSubCategoryDTO()
        {
        }

        public tblSubCategoryDTO(Int32 subCategoryId, Int32 categoryId, Int32 languageId, String subCategoryName, String description, String logo, Boolean isActive, Boolean isDeleted)
        {
			this.SubCategoryId = subCategoryId;
			this.CategoryId = categoryId;
			this.LanguageId = languageId;
			this.SubCategoryName = subCategoryName;
			this.Description = description;
			this.Logo = logo;
			this.IsActive = isActive;
			this.IsDeleted = isDeleted;
        }
    }
}
