//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-05-07 - 11:56:52
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace OrderWala.Domain
{
    [DataContract()]
    public partial class tblSubCategoryDTO
    {

        public tblSubCategoryDTO()
        {
            categorylist = new List<tblLanguageWiseCategoryDTO>();         
            LanguageList = new List<tblLanguageDTO>();
        }

        [DataMember()]
        public Int32 SubCategoryId { get; set; }

        [DataMember()]
        public Int32 CategoryId { get; set; }

        public String CategoryName { get; set; }

        [DataMember()]
        public String Logo { get; set; }

        [DataMember()]
        public Boolean IsActive { get; set; }

        [DataMember()]
        public Boolean IsDeleted { get; set; }

        [DataMember()]
        public String SubCategoryName { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public Int32 LanguageId { get; set; }

        public Int32 RowId { get; set; }  

        public List<tblLanguageWiseCategoryDTO> categorylist { get; set; }

         public List<tblLanguageDTO> LanguageList { get; set; }
    }
}
