//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderWala.Domain.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderWalaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderWalaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrderWala.Domain.Resource.OrderWalaResource", typeof(OrderWalaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your mobile number is already register with us..
        /// </summary>
        public static string msgDuplicateUserName {
            get {
                return ResourceManager.GetString("msgDuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration faild please contact admin for more detail..
        /// </summary>
        public static string msgErrorInRegistration {
            get {
                return ResourceManager.GetString("msgErrorInRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in transaction please try again later..
        /// </summary>
        public static string msgErrorInTransaction {
            get {
                return ResourceManager.GetString("msgErrorInTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password..
        /// </summary>
        public static string valInvalidLoginDetail {
            get {
                return ResourceManager.GetString("valInvalidLoginDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select area..
        /// </summary>
        public static string valRequiredArea {
            get {
                return ResourceManager.GetString("valRequiredArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter first name..
        /// </summary>
        public static string valRequiredFirstName {
            get {
                return ResourceManager.GetString("valRequiredFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter last name..
        /// </summary>
        public static string valRequiredLastName {
            get {
                return ResourceManager.GetString("valRequiredLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your location in google map..
        /// </summary>
        public static string valRequiredMapAddress {
            get {
                return ResourceManager.GetString("valRequiredMapAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter mobile no..
        /// </summary>
        public static string valRequiredMobileNo {
            get {
                return ResourceManager.GetString("valRequiredMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password..
        /// </summary>
        public static string valRequiredPassword {
            get {
                return ResourceManager.GetString("valRequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter username..
        /// </summary>
        public static string valRequiredUserName {
            get {
                return ResourceManager.GetString("valRequiredUserName", resourceCulture);
            }
        }
    }
}
