//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderWala.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrderWalaEntities : DbContext
    {
        public OrderWalaEntities()
            : base("name=OrderWalaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblAdvertisement> tblAdvertisements { get; set; }
        public DbSet<tblArea> tblAreas { get; set; }
        public DbSet<tblCategory> tblCategories { get; set; }
        public DbSet<tblCity> tblCities { get; set; }
        public DbSet<tblCustomer> tblCustomers { get; set; }
        public DbSet<tblCustomerPayment> tblCustomerPayments { get; set; }
        public DbSet<tblDeliveryCharge> tblDeliveryCharges { get; set; }
        public DbSet<tblLanguage> tblLanguages { get; set; }
        public DbSet<tblLanguageWiseProduct> tblLanguageWiseProducts { get; set; }
        public DbSet<tblLogin> tblLogins { get; set; }
        public DbSet<tblOrder> tblOrders { get; set; }
        public DbSet<tblOrderItem> tblOrderItems { get; set; }
        public DbSet<tblProduct> tblProducts { get; set; }
        public DbSet<tblProductPrice> tblProductPrices { get; set; }
        public DbSet<tblQuantityType> tblQuantityTypes { get; set; }
        public DbSet<tblState> tblStates { get; set; }
        public DbSet<tblSubCategory> tblSubCategories { get; set; }
        public DbSet<tblUserType> tblUserTypes { get; set; }
    }
}
