//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderWala.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public int CustomerId { get; set; }
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public int AreaId { get; set; }
        public string EmailAddress { get; set; }
        public string MobileNo { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public double TotalOrderAmount { get; set; }
        public double RecievedAmount { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public Nullable<int> RegisterDeviceId { get; set; }
    }
}
