//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderWala.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeliveryCharge
    {
        public int DeliveryChargesId { get; set; }
        public double StartAmount { get; set; }
        public double EndAmount { get; set; }
        public double Charges { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreationDateTime { get; set; }
    }
}
