//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderWala.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderItem
    {
        public int OrderItemId { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public double Price { get; set; }
        public double Discount { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public int Status { get; set; }
    }
}
