//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrderManagmentEntities : DbContext
    {
        public OrderManagmentEntities()
            : base("name=OrderManagmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TblAddressMaster> TblAddressMasters { get; set; }
        public DbSet<TblAdminLoginMaster> TblAdminLoginMasters { get; set; }
        public DbSet<TblBillMaster> TblBillMasters { get; set; }
        public DbSet<TblCategoryMaster> TblCategoryMasters { get; set; }
        public DbSet<TblCustomerCreditMaster> TblCustomerCreditMasters { get; set; }
        public DbSet<TblCustomerDeviceMaster> TblCustomerDeviceMasters { get; set; }
        public DbSet<TblCustomerMaster> TblCustomerMasters { get; set; }
        public DbSet<TblCustomerPaymentDetailMaster> TblCustomerPaymentDetailMasters { get; set; }
        public DbSet<TblCustomerStatusMaster> TblCustomerStatusMasters { get; set; }
        public DbSet<TblDeviceTypeMaster> TblDeviceTypeMasters { get; set; }
        public DbSet<TblEmployeeMaster> TblEmployeeMasters { get; set; }
        public DbSet<TblEmployeeTypeMaster> TblEmployeeTypeMasters { get; set; }
        public DbSet<TblLanguageMaster> TblLanguageMasters { get; set; }
        public DbSet<TblOrderItemDetailMaster> TblOrderItemDetailMasters { get; set; }
        public DbSet<TblOrderMaster> TblOrderMasters { get; set; }
        public DbSet<TblOrderStatusMaster> TblOrderStatusMasters { get; set; }
        public DbSet<TblProductMaster> TblProductMasters { get; set; }
        public DbSet<TblProductStatusMaster> TblProductStatusMasters { get; set; }
        public DbSet<TblSubCategoryMaster> TblSubCategoryMasters { get; set; }
        public DbSet<TblSupplierDeviceMaster> TblSupplierDeviceMasters { get; set; }
        public DbSet<TblSupplierMaster> TblSupplierMasters { get; set; }
        public DbSet<TblTerm_ConditionMaster> TblTerm_ConditionMaster { get; set; }
        public DbSet<TblTypeMaster> TblTypeMasters { get; set; }
        public DbSet<TblUserLoginMaster> TblUserLoginMasters { get; set; }
        public DbSet<TblUserLogMaster> TblUserLogMasters { get; set; }
    }
}
